fish = input("what type of fish do you want?")
if fish == ("its carniviorous")
if ("they already have it,")
        print ("too bad")
if fish == ("they dont")
    print ("enjoy")
elif  ("its salt water")
    print ("you're a fancy fish parent")
elif fish == ("community")
    print ("you should get more than one")
else
    print ("i dont think thats a kind of fish")
